apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../aggregate

patchesJson6902:
  - path: patch-resources.yaml
    target:
      group: platform.stackrox.io
      kind: Central
      name: central
      version: v1alpha1