kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../default

patchesJson6902:
  - path: patch-source-and-name.yaml
    target:
      group: costmanagement-metrics-cfg.openshift.io/v1beta1
      kind: CostManagementMetricsConfig
      name: instance
      version: v1beta1
