# Note this is resource reduced, this should not be taken as a production ready installation
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: central
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 500Mi
      scaling:
        autoScaling: Disabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 2
    db:
      resources:
        limits:
          cpu: '1'
          memory: '1'
        requests:
          cpu: '1'
          memory: '1'
    scannerComponent: Enabled
