apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

bases:
  - ../../base

patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1alpha1
    kind: Subscription
    name: ocs-operator
    namespace: openshift-storage
  path: patch-channel.yaml
- target:
    group: operators.coreos.com
    version: v1
    kind: OperatorGroup
    name: openshift-storage
    namespace: openshift-storage
  path: patch-operatorgroup.yaml